POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "username":"admin",
    "password":"secret"
}



###

GET http://127.0.0.1:8000/api/github-users?usernames=monettayy,monettay,monette
Content-Type: application/json
Authorization: Bearer 1|LbsaxGWMAyJ8pvp8XFSZTNoNWOCqtsuADEakWGOZ



### 

POST http://127.0.0.1:8000/api/logout
Content-Type: application/json
Authorization: Bearer 4|n63Cu1Pc9lFh5MgSw8Yy1dkgs9VPHKqaWFqtetiX



###

GET http://127.0.0.1:8000/api/hamming-distance/compute?x=1&y=4
Content-Type: application/json
